# Generated by Django 5.0.4 on 2024-05-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserSignup",
            new_name="UserDetails",
        ),
        migrations.DeleteModel(
            name="UserLogin",
        ),
        migrations.AddField(
            model_name="card",
            name="userid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.userdetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="column",
            name="name",
            field=models.CharField(default="cards", max_length=200),
        ),
    ]
