# Generated by Django 5.0.4 on 2024-05-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_card_order_alter_card_column"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="column",
            name="length",
        ),
        migrations.AlterField(
            model_name="column",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
